image: timbru31/java-node
cache:
  paths:
  - node_modules/

before_script:
        - cd course-snippet-app-ui
        - npm install copyfiles -g
        - npm install
        - npm run build
        - cd ..
buildapp:
        script:
                - cd course-snippet-app-backend
                - mvn clean package
        
