image: timbru31/java-node
cache:
  paths:
  - node_modules/

before_script:
        - npm --version
build-angular:
        script:
                - cd course-snippet-app-ui
                - npm install copyfiles -g
                - npm install
                - npm run build
                - cd ..        
build-maven:
        script:
                - cd course-snippet-app-backend
                - ./mvnw clean package
        
