image: node:9.8.0
cache:
  paths:
  - node_modules/

before_script:
        - cd course-snippet-app-ui
        - npm install
        - npm run build
        - cd..
buildapp:
        script:
                - cd course-snippet-app-backend
                - mvn clean package
        
