before_script:
        - yum install -y gcc-c++ make
        - curl -sL https://rpm.nodesource.com/setup_6.x | sudo -E bash -
        - yum install nodejs  
        - cd course-snippet-app-ui
        - npm install
        - npm run build
        - cd..
buildapp:
        script:
                - cd course-snippet-app-backend
                - mvn clean package
        
