before_script:
        - cd course-snippet-app-ui
        - npm install
        - npm run build
        - cd..
buildapp:
        script:
                - cd course-snippet-app-backend
                - mvn clean package
        
